CREATE TABLE "GCG_4243_Ship_Schd"(
 "BIRUNID" BIGINT NOT NULL ,
 "ORDER_NO" CHAR(7),
 "ORDER_SUFFIX" CHAR(4),
 "CUSTOMER" CHAR(6),
 "PART" CHAR(20),
 "ADDRESS_1_SHIP" CHAR(30),
 "CITY_SHIP" CHAR(15),
 "STATE_SHIP" CHAR(2),
 "COUNTRY_SHIP" CHAR(12),
 "DATE_SHIPPED" DATE);