CREATE TABLE "GCG_4243_FREIGHTCOST"(
"ORDER_NO" CHAR(7),
"ORDER_SUFFIX" CHAR(4),
"DRIVER" CHAR(30),
"TRUCK_NO" CHAR(30),
"TRAILER_NO" CHAR(30),
"PILOT_COST" DOUBLE,
"PERMIT_COST" DOUBLE,
"COST_PER_MILE" DOUBLE,
"CUSTOMER_ACCPT" BIT);